# Generated by Django 4.2.6 on 2023-11-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_bookingform_processed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='status',
            field=models.CharField(choices=[('new', 'Нові'), ('needs_confirmation', 'Потребують підтвердження'), ('confirmed', 'Підтверджені'), ('rejected', 'Відхилені'), ('acquisition_today', 'Отримання сьогодні'), ('rental_failed', 'Прокат зірваний'), ('returning_today', 'Повернення сьогодні'), ('rental_successful', 'Прокат успішний')], default='new', max_length=20),
        ),
    ]
