# Generated by Django 4.2.6 on 2023-11-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_bookingform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingform',
            name='comment',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='status',
            field=models.CharField(choices=[('new', 'Нові'), ('needs_confirmation', 'Потребують підтвердження'), ('confirmed', 'Підтверджені'), ('rejected', 'Відхилені'), ('acquisition_today', 'Отримання сьогодні'), ('rental_failed', 'Прокат зірваний'), ('in_rental', 'В прокаті'), ('returning_today', 'Повернення сьогодні'), ('rental_successful', 'Прокат успішний')], default='new', max_length=20),
        ),
    ]
