# Generated by Django 4.2.6 on 2023-11-11 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_bookingform_child_seat_bookingform_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingform',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
