# Generated by Django 4.2.6 on 2023-12-04 16:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0006_bookingform_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='email',
            field=models.EmailField(blank=True, max_length=320, null=True),
        ),
        migrations.AlterField(
            model_name='bookingform',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(13)]),
        ),
    ]
