# Generated by Django 4.2.6 on 2023-10-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('economy', 'Бюджетні'), ('comfort', 'Комфорт'), ('crossover', 'Кросовери'), ('business', 'Бізнес'), ('sport', 'Спорт'), ('prem_4x4', 'Преміум 4х4')], default='business', max_length=10),
        ),
    ]
